### ISSUE TITLE
Use human-readable names in JSON output for enumerated types

### ISSUE THREAD

**Issue by nutjob4life** [MCLConsortium/mcl.sickbay#16]
Because reasons

**Comment by nutjob4life** [comment]
@yuliujpl @asitang 

Here's what I'm proposing. Right now, for enumerated types, you get the computerized token value (suitable for code) over the JSON:

```json
{
         "mitotic_rate" : "two_to_20",
         "ajcc_extent_of_invasion_primary_tumor" : "pt3a",
         "her2_immunohistochemistry" : "positive_score_3_plus"
}
```
Now you would get:
```json
{
         "mitotic_rate" : {
            "label" : "2 to 20 mitoses/mm²",
            "token" : "two_to_20"
         },
         "ajcc_extent_of_invasion_primary_tumor" : {
            "label" : "pT3a: Extraprostatic extension or microscopic bladder neck invasion",
            "token" : "pt3a"
         },
         "her2_immunohistochemistry" : {
            "label" : "Positive (Score 3+)",
            "token" : "positive_score_3_plus"
         }
}
```
This would apply only to _enumerations_; simple numbers or strings wouldn't be affected.

If this is okay I'll make it happen.

**Comment by asitang** [comment]
@nutjob4life does this change anything in the introspection or the publishing code? 
This changes just what David receives from the REST API right?

**Comment by nutjob4life** [comment]
@asitang correct! This only affects JSON generation. The model stays the same so the publishing part can rely on a stable interface.

**Comment by asitang** [comment]
@nutjob4life this change is good with me :)

**Comment by nutjob4life** [comment]
Thanks @asitang!

Does this look okay to you @yuliujpl ?

**Comment by yuliujpl** [comment]
Looks great to me, thanks for referencing this Sean! I can certainly set up the ability to display the right values on my end!

**Comment by nutjob4life** [comment]
Okay @yuliujpl  this is now live.

The following URLs are available:

- https://mcl.jpl.nasa.gov/infirmary/ … 301 redirect to ↓
- https://mcl.jpl.nasa.gov/infirmary/v1/ … this is the API you already use, so nothing should break
- https://mcl.jpl.nasa.gov/infirmary/v2/ … this is the new API that includes human-readable labels as described above
