### ISSUE TITLE
Add inscribed_ fields for PriorLesion and AdjacentSpecimen

### ISSUE THREAD

**Issue by asitang** [MCLConsortium/mcl.sickbay#3]
AttributeError: type object 'PriorLesion' has no attribute 'inscribed_clinicalCore_participant_ID'
AttributeError: type object 'AdjacentSpecimen' has no attribute 'inscribed_biospecimen_identifier'

**Comment by nutjob4life** [comment]
Do you really need `inscribed_clinicalCore_participant_ID` on `PriorLesion`? I figure you'd just make them as you parse the `|`-separated lesions in a `clinicacore` spreadsheet; you never will encounter them separately or out-of-order, right @asitang?

(FYI, I'm going ahead and adding them.)
